services:
  - type: web
    name: gonaturefarms-backend
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DB_HOST
        fromDatabase:
          name: gonaturefarms-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gonaturefarms-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: gonaturefarms-db
          property: databaseName
      - key: DB_USER
        fromDatabase:
          name: gonaturefarms-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gonaturefarms-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://gonaturefarms-frontend-fvn3mbf18-gonatuefarms.vercel.app
      - key: ADMIN_DEFAULT_USER
        value: Vishnu
      - key: ADMIN_DEFAULT_PASS
        value: 918252

databases:
  - name: gonaturefarms-db
    databaseName: gnf_y4iw
    user: gnf_y4iw_user
    plan: free
