services:
  - type: web
    name: gonaturefarms-backend
    runtime: docker
    plan: free
    envVars:
      - key: PGHOST
        fromDatabase:
          name: gonaturefarms-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: gonaturefarms-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: gonaturefarms-db
          property: databaseName
      - key: PGUSER
        fromDatabase:
          name: gonaturefarms-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: gonaturefarms-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://gonaturefarms-frontend-fvn3mbf18-gonatuefarms.vercel.app
      - key: ADMIN_DEFAULT_USER
        value: Vishnu
      - key: ADMIN_DEFAULT_PASS
        value: 918252

databases:
  - name: gonaturefarms-db
    databaseName: gnf_y4iw
    user: gnf_y4iw_user
    plan: free
